name = "github-readme-attack-pulse"
main = "src/index.ts"
compatibility_date = "2026-07-01"
workers_dev = true
preview_urls = false

[[kv_namespaces]]
binding = "ATTACK_PULSE_CACHE"
id = "5c03986bb4bf459998337992bd301527"
